const profiles = [
  {
    keys: ["frontend", "front end", "vue", "react", "web developer"],
    title: "Frontend Developer",
    skills: [
      "JavaScript",
      "TypeScript",
      "Vue.js",
      "React",
      "HTML5",
      "CSS3",
      "Responsive Design",
      "REST APIs",
      "Git",
      "Vite",
      "Accessibility",
      "Testing",
    ],
    keywords: [
      "component architecture",
      "performance",
      "accessibility",
      "responsive design",
      "REST APIs",
      "state management",
      "Git",
      "testing",
    ],
    responsibilities: [
      "Built responsive, accessible interfaces from product requirements and design systems.",
      "Created reusable components and improved front-end maintainability.",
      "Integrated REST APIs and handled loading, error and empty states.",
      "Improved page performance and user experience across desktop and mobile.",
    ],
    summary:
      "Frontend Developer focused on building fast, accessible and maintainable web applications. Experienced with modern JavaScript frameworks, reusable component architecture, API integration and responsive UI delivery.",
  },
  {
    keys: ["backend", "back end", "node", "api developer"],
    title: "Backend Developer",
    skills: [
      "Node.js",
      "Express",
      "REST APIs",
      "SQL",
      "PostgreSQL",
      "MongoDB",
      "Authentication",
      "Docker",
      "Git",
      "Testing",
      "Redis",
      "System Design",
    ],
    keywords: [
      "API design",
      "databases",
      "authentication",
      "scalability",
      "performance",
      "security",
      "testing",
      "system design",
    ],
    responsibilities: [
      "Designed and maintained secure REST APIs and backend services.",
      "Modeled relational data and optimized database queries.",
      "Implemented authentication, validation and error handling.",
      "Improved service reliability through testing, logging and monitoring.",
    ],
    summary:
      "Backend Developer experienced in building reliable APIs, database-driven services and secure application infrastructure with a strong focus on maintainability, performance and clean architecture.",
  },
  {
    keys: [
      "full stack",
      "fullstack",
      "software engineer",
      "software developer",
    ],
    title: "Full Stack Developer",
    skills: [
      "JavaScript",
      "TypeScript",
      "Vue.js",
      "React",
      "Node.js",
      "REST APIs",
      "SQL",
      "PostgreSQL",
      "Git",
      "Docker",
      "Testing",
      "CI/CD",
    ],
    keywords: [
      "full stack",
      "frontend",
      "backend",
      "API integration",
      "database design",
      "testing",
      "deployment",
      "agile",
    ],
    responsibilities: [
      "Delivered end-to-end web features across frontend, backend and database layers.",
      "Designed reusable UI components and production-ready API endpoints.",
      "Collaborated with product stakeholders to turn requirements into shipped features.",
      "Improved code quality through reviews, testing and documentation.",
    ],
    summary:
      "Full Stack Developer with hands-on experience delivering complete web products across frontend, backend and database layers. Strong in modern JavaScript, API design, data modeling and maintainable product development.",
  },
  {
    keys: ["data analyst", "business analyst", "analyst"],
    title: "Data Analyst",
    skills: [
      "Excel",
      "SQL",
      "Power BI",
      "Tableau",
      "Python",
      "Data Cleaning",
      "Data Visualization",
      "Dashboarding",
      "Statistics",
      "Reporting",
      "Data Modeling",
      "KPI Analysis",
    ],
    keywords: [
      "dashboards",
      "SQL",
      "KPIs",
      "reporting",
      "data visualization",
      "insights",
      "forecasting",
      "stakeholders",
    ],
    responsibilities: [
      "Built dashboards and recurring reports to track operational and business KPIs.",
      "Cleaned, validated and analyzed datasets using SQL, spreadsheets and BI tools.",
      "Translated analysis into clear recommendations for business stakeholders.",
      "Automated recurring reporting tasks to improve speed and consistency.",
    ],
    summary:
      "Data Analyst experienced in transforming raw data into clear business insights through SQL, dashboards, reporting and data visualization. Skilled at communicating findings and supporting data-driven decisions.",
  },
  {
    keys: ["data scientist", "machine learning", "ml engineer"],
    title: "Data Scientist",
    skills: [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "SQL",
      "Machine Learning",
      "Statistics",
      "Data Visualization",
      "Feature Engineering",
      "Jupyter",
      "Model Evaluation",
      "Git",
    ],
    keywords: [
      "machine learning",
      "modeling",
      "feature engineering",
      "statistics",
      "experimentation",
      "prediction",
      "data pipelines",
    ],
    responsibilities: [
      "Developed predictive models and evaluated performance against business goals.",
      "Prepared datasets through cleaning, feature engineering and exploratory analysis.",
      "Communicated model findings and tradeoffs to technical and non-technical stakeholders.",
      "Built repeatable analysis workflows and model evaluation pipelines.",
    ],
    summary:
      "Data Scientist with experience in statistical analysis, machine learning and data storytelling. Skilled in turning complex datasets into predictive models, measurable insights and practical recommendations.",
  },
  {
    keys: ["accountant", "accounting", "bookkeeper", "finance"],
    title: "Accountant",
    skills: [
      "Financial Reporting",
      "General Ledger",
      "Accounts Payable",
      "Accounts Receivable",
      "Reconciliation",
      "Excel",
      "QuickBooks",
      "Budgeting",
      "Tax Preparation",
      "Month-End Close",
      "GAAP",
      "Variance Analysis",
    ],
    keywords: [
      "reconciliation",
      "financial reporting",
      "month-end close",
      "ledger",
      "AP",
      "AR",
      "budgeting",
      "compliance",
    ],
    responsibilities: [
      "Prepared and reviewed financial statements, reconciliations and journal entries.",
      "Managed accounts payable and receivable while maintaining accurate records.",
      "Supported month-end close and investigated account variances.",
      "Improved reporting accuracy through standardized controls and spreadsheet automation.",
    ],
    summary:
      "Detail-oriented Accountant experienced in financial reporting, reconciliations, general ledger activities and month-end close. Known for accuracy, organized processes and clear financial reporting.",
  },
  {
    keys: ["marketing", "digital marketing", "social media", "seo"],
    title: "Digital Marketing Specialist",
    skills: [
      "Digital Marketing",
      "SEO",
      "Google Analytics",
      "Content Strategy",
      "Social Media",
      "Email Marketing",
      "Paid Ads",
      "Google Ads",
      "Meta Ads",
      "Copywriting",
      "Campaign Analysis",
      "A/B Testing",
    ],
    keywords: [
      "campaigns",
      "conversion",
      "SEO",
      "content",
      "analytics",
      "paid media",
      "engagement",
      "ROI",
    ],
    responsibilities: [
      "Planned and executed multi-channel campaigns across paid, organic and email channels.",
      "Tracked campaign performance and optimized spend using conversion and engagement data.",
      "Created content calendars and coordinated campaign assets.",
      "Used testing and analytics to improve click-through and conversion rates.",
    ],
    summary:
      "Digital Marketing Specialist experienced in campaign strategy, content, paid media and analytics. Focused on measurable growth, audience engagement and continuous optimization across digital channels.",
  },
  {
    keys: [
      "sales",
      "account executive",
      "business development",
      "sales representative",
    ],
    title: "Sales Professional",
    skills: [
      "Prospecting",
      "Lead Generation",
      "CRM",
      "Salesforce",
      "Negotiation",
      "Pipeline Management",
      "Account Management",
      "Cold Outreach",
      "Presentation",
      "Closing",
      "Forecasting",
      "Customer Relationships",
    ],
    keywords: [
      "quota",
      "pipeline",
      "revenue",
      "prospecting",
      "closing",
      "CRM",
      "accounts",
      "negotiation",
    ],
    responsibilities: [
      "Managed sales pipeline from prospecting through negotiation and close.",
      "Built long-term customer relationships and identified expansion opportunities.",
      "Maintained accurate CRM activity, forecasts and account notes.",
      "Consistently prioritized high-value opportunities to support revenue targets.",
    ],
    summary:
      "Results-focused Sales Professional with experience in prospecting, pipeline management, customer relationships and closing. Skilled at understanding customer needs and turning opportunities into sustainable revenue.",
  },
  {
    keys: ["project manager", "project management", "scrum master"],
    title: "Project Manager",
    skills: [
      "Project Planning",
      "Agile",
      "Scrum",
      "Risk Management",
      "Stakeholder Management",
      "Jira",
      "Budget Management",
      "Roadmaps",
      "Resource Planning",
      "Status Reporting",
      "Facilitation",
      "Process Improvement",
    ],
    keywords: [
      "delivery",
      "stakeholders",
      "risk",
      "timeline",
      "budget",
      "agile",
      "cross-functional",
      "planning",
    ],
    responsibilities: [
      "Led cross-functional projects from planning through delivery and closeout.",
      "Managed scope, timelines, risks, dependencies and stakeholder communication.",
      "Facilitated project rituals and resolved blockers across teams.",
      "Created status reporting and delivery plans to improve visibility and accountability.",
    ],
    summary:
      "Project Manager experienced in coordinating cross-functional teams, managing timelines and risks, and delivering initiatives with clear stakeholder communication and structured execution.",
  },
  {
    keys: ["product manager", "product owner"],
    title: "Product Manager",
    skills: [
      "Product Strategy",
      "Roadmapping",
      "User Research",
      "Prioritization",
      "Analytics",
      "Agile",
      "Jira",
      "Product Discovery",
      "Requirements",
      "A/B Testing",
      "Stakeholder Management",
      "Go-to-Market",
    ],
    keywords: [
      "roadmap",
      "user research",
      "prioritization",
      "product strategy",
      "metrics",
      "discovery",
      "experiments",
      "stakeholders",
    ],
    responsibilities: [
      "Owned product roadmap and prioritized work against user and business outcomes.",
      "Translated customer insights into clear requirements and product opportunities.",
      "Partnered with design and engineering from discovery through launch.",
      "Tracked product metrics and used experiments to guide iteration.",
    ],
    summary:
      "Product Manager focused on turning customer needs and business goals into clear product strategy, prioritized roadmaps and measurable product outcomes through strong cross-functional collaboration.",
  },
  {
    keys: ["ux", "ui", "product designer", "designer"],
    title: "UX/UI Designer",
    skills: [
      "Figma",
      "User Research",
      "Wireframing",
      "Prototyping",
      "Design Systems",
      "Usability Testing",
      "Interaction Design",
      "Responsive Design",
      "Information Architecture",
      "Accessibility",
      "Journey Mapping",
      "Visual Design",
    ],
    keywords: [
      "user research",
      "prototyping",
      "design systems",
      "usability",
      "accessibility",
      "wireframes",
      "product design",
    ],
    responsibilities: [
      "Designed user flows, wireframes and high-fidelity interfaces for web and mobile experiences.",
      "Built reusable design-system components and documented interaction patterns.",
      "Conducted usability testing and iterated designs using user feedback.",
      "Collaborated closely with product and engineering throughout implementation.",
    ],
    summary:
      "UX/UI Designer experienced in user-centered product design, prototyping, design systems and usability testing. Focused on creating intuitive, accessible and visually polished digital experiences.",
  },
  {
    keys: ["human resources", "hr", "recruiter", "talent acquisition"],
    title: "Human Resources Specialist",
    skills: [
      "Recruiting",
      "Onboarding",
      "Employee Relations",
      "HRIS",
      "Performance Management",
      "Talent Acquisition",
      "Policy Administration",
      "Training",
      "Compliance",
      "Interviewing",
      "Benefits Administration",
      "Workforce Planning",
    ],
    keywords: [
      "recruiting",
      "onboarding",
      "employee relations",
      "HRIS",
      "compliance",
      "performance",
      "talent",
    ],
    responsibilities: [
      "Coordinated recruiting, interviews, offers and employee onboarding.",
      "Maintained HR records, policies and employee lifecycle documentation.",
      "Supported employee relations and performance-management processes.",
      "Improved HR workflows through better documentation and standardized processes.",
    ],
    summary:
      "Human Resources Specialist with experience across recruiting, onboarding, employee relations and HR operations. Skilled at building organized people processes and supporting a positive employee experience.",
  },
  {
    keys: ["customer service", "customer support", "support specialist"],
    title: "Customer Support Specialist",
    skills: [
      "Customer Service",
      "Ticketing Systems",
      "CRM",
      "Zendesk",
      "Troubleshooting",
      "Email Support",
      "Live Chat",
      "Escalation Management",
      "Knowledge Base",
      "Customer Retention",
      "Communication",
      "SLA Management",
    ],
    keywords: [
      "customer satisfaction",
      "tickets",
      "SLA",
      "resolution",
      "support",
      "escalation",
      "retention",
    ],
    responsibilities: [
      "Resolved customer questions across email, chat and ticketing channels.",
      "Investigated product issues and coordinated escalations when needed.",
      "Maintained clear case notes and followed service-level expectations.",
      "Identified recurring customer issues and contributed to help-center improvements.",
    ],
    summary:
      "Customer Support Specialist known for clear communication, efficient issue resolution and a customer-first approach. Experienced with ticketing systems, troubleshooting, escalations and support documentation.",
  },
  {
    keys: [
      "operations",
      "operations manager",
      "office manager",
      "administrator",
      "administrative assistant",
    ],
    title: "Operations Specialist",
    skills: [
      "Operations Management",
      "Process Improvement",
      "Excel",
      "Reporting",
      "Scheduling",
      "Vendor Coordination",
      "Documentation",
      "KPI Tracking",
      "SOPs",
      "Cross-functional Coordination",
      "Budget Tracking",
      "Problem Solving",
    ],
    keywords: [
      "operations",
      "process improvement",
      "SOPs",
      "KPI",
      "coordination",
      "reporting",
      "efficiency",
    ],
    responsibilities: [
      "Coordinated daily operational workflows and cross-functional requests.",
      "Created SOPs and improved recurring processes for consistency and efficiency.",
      "Tracked operational KPIs and prepared management reports.",
      "Coordinated vendors, schedules and administrative requirements.",
    ],
    summary:
      "Operations Specialist experienced in process coordination, reporting, documentation and continuous improvement. Focused on creating efficient workflows, reliable execution and clear operational visibility.",
  },
  {
    keys: [
      "cybersecurity",
      "security analyst",
      "soc analyst",
      "information security",
    ],
    title: "Cybersecurity Analyst",
    skills: [
      "SIEM",
      "Incident Response",
      "Vulnerability Management",
      "Network Security",
      "Security Monitoring",
      "Splunk",
      "IAM",
      "Risk Assessment",
      "NIST",
      "Linux",
      "Threat Analysis",
      "Security Awareness",
    ],
    keywords: [
      "incident response",
      "SIEM",
      "vulnerability",
      "monitoring",
      "risk",
      "threats",
      "security controls",
    ],
    responsibilities: [
      "Monitored security alerts and investigated suspicious activity.",
      "Supported incident response, documentation and post-incident review.",
      "Tracked vulnerabilities and coordinated remediation with system owners.",
      "Maintained security controls and contributed to risk assessments.",
    ],
    summary:
      "Cybersecurity Analyst experienced in security monitoring, incident response, vulnerability management and risk analysis. Focused on reducing exposure through disciplined investigation and practical security controls.",
  },
  {
    keys: ["devops", "cloud engineer", "site reliability", "sre"],
    title: "DevOps Engineer",
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Linux",
      "Terraform",
      "GitHub Actions",
      "Monitoring",
      "Bash",
      "Networking",
      "Infrastructure as Code",
      "Cloud Security",
    ],
    keywords: [
      "CI/CD",
      "cloud",
      "automation",
      "infrastructure",
      "containers",
      "monitoring",
      "reliability",
      "deployment",
    ],
    responsibilities: [
      "Automated build, test and deployment workflows through CI/CD pipelines.",
      "Managed cloud infrastructure using infrastructure-as-code practices.",
      "Improved application observability through logging, metrics and alerting.",
      "Partnered with engineering teams to improve deployment reliability and operational readiness.",
    ],
    summary:
      "DevOps Engineer experienced in cloud infrastructure, CI/CD, containers and automation. Focused on reliable deployments, observable systems and scalable infrastructure practices.",
  },
];

const generic = {
  title: "Professional",
  skills: [
    "Communication",
    "Problem Solving",
    "Teamwork",
    "Time Management",
    "Project Coordination",
    "Microsoft Office",
    "Documentation",
    "Customer Focus",
    "Adaptability",
    "Attention to Detail",
  ],
  keywords: [
    "communication",
    "results",
    "collaboration",
    "planning",
    "quality",
    "customers",
    "improvement",
  ],
  responsibilities: [
    "Delivered high-quality work while managing priorities and deadlines.",
    "Collaborated with colleagues and stakeholders to achieve team goals.",
    "Improved day-to-day processes through clear documentation and follow-through.",
    "Resolved issues proactively and maintained strong attention to detail.",
  ],
  summary:
    "Results-oriented professional with a strong record of reliable execution, clear communication and continuous improvement. Experienced in collaborating across teams, solving problems and delivering high-quality work.",
};

export function findJobProfile(title = "") {
  const q = title.toLowerCase().trim();
  if (!q) return generic;
  return (
    profiles.find((p) => p.keys.some((k) => q.includes(k))) || {
      ...generic,
      title: title.trim() || generic.title,
    }
  );
}

export function makeSummary(title, resume) {
  const p = findJobProfile(title);
  const skills = (resume?.skills || []).filter(Boolean).slice(0, 5);
  if (!skills.length) return p.summary.replace(p.title, title || p.title);
  return `${title || p.title} with experience across ${skills.join(", ")}. Focused on measurable results, clear communication and high-quality execution, with a practical approach to collaboration and continuous improvement.`;
}

export function suggestedSkills(title = "") {
  return findJobProfile(title).skills;
}
export function suggestedResponsibilities(title = "") {
  return findJobProfile(title).responsibilities;
}
export function suggestedKeywords(title = "") {
  return findJobProfile(title).keywords;
}
