<script setup>
import { computed, ref, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ResumePreview from '../components/ResumePreview.vue'
import CareerAssistant from '../components/CareerAssistant.vue'
import ThemeToggle from '../components/ThemeToggle.vue'
import { getResume, updateResume } from '../services/data'
import { suggestedResponsibilities } from '../utils/jobProfiles'
import { translateResume } from '../utils/resumeTranslator'
import { resumeTemplates, atsTemplateIds } from '../utils/templates'

const route = useRoute(); const router = useRouter(); const id = route.params.id
const title = ref('Untitled Resume'); const template = ref('ats-modern'); const saving = ref(false); const saved = ref(false); const error = ref('')
const cvLanguage = ref('en'); const showLanguageMenu = ref(false); const showTypography = ref(false); let timer = null

const arabicFonts = [
  { id: 'Tajawal', name: 'Tajawal', sample: 'سيرة ذاتية احترافية' }, { id: 'Cairo', name: 'Cairo', sample: 'خبرات ومهارات مميزة' },
  { id: 'IBM Plex Sans Arabic', name: 'IBM Plex Sans Arabic', sample: 'تصميم عصري واحترافي' }, { id: 'Noto Kufi Arabic', name: 'Noto Kufi Arabic', sample: 'وضوح وأناقة عالية' },
  { id: 'Almarai', name: 'Almarai', sample: 'أسلوب هادئ ورسمي' }, { id: 'Changa', name: 'Changa', sample: 'طابع حديث ومميز' }
]
const englishFonts = [
  { id: 'Manrope', name: 'Manrope', sample: 'Modern professional resume' }, { id: 'Inter', name: 'Inter', sample: 'Clean and highly readable' },
  { id: 'DM Sans', name: 'DM Sans', sample: 'Smart and contemporary' }, { id: 'Montserrat', name: 'Montserrat', sample: 'Bold corporate presence' },
  { id: 'Playfair Display', name: 'Playfair Display', sample: 'Elegant executive style' }, { id: 'Lora', name: 'Lora', sample: 'Refined editorial look' }
]
const resume = ref({ personal:{name:'',title:'',email:'',phone:'',location:'',summary:'',website:'',linkedin:''}, experience:[],education:[],skills:[],projects:[],languages:[],design:{fontEn:'Manrope',fontAr:'Tajawal'} })
const atsTemplates = atsTemplateIds
const atsOptions = resumeTemplates.filter(t=>t.kind==='ATS Friendly'); const creativeOptions = resumeTemplates.filter(t=>t.kind==='Creative')
const activeFont = computed(()=>cvLanguage.value==='ar'?(resume.value.design?.fontAr||'Tajawal'):(resume.value.design?.fontEn||'Manrope'))
const activeFontList = computed(()=>cvLanguage.value==='ar'?arabicFonts:englishFonts)
function setResumeFont(font){if(!resume.value.design)resume.value.design={fontEn:'Manrope',fontAr:'Tajawal'};if(cvLanguage.value==='ar')resume.value.design.fontAr=font;else resume.value.design.fontEn=font}
function ensureShape(d={}){cvLanguage.value=d.language||cvLanguage.value||'en';return{language:d.language||cvLanguage.value,personal:{name:'',title:'',email:'',phone:'',location:'',summary:'',website:'',linkedin:'',...(d.personal||{})},experience:d.experience||[],education:d.education||[],skills:d.skills||[],projects:d.projects||[],languages:d.languages||[],design:{fontEn:'Manrope',fontAr:'Tajawal',...(d.design||{})}}}
async function load(){try{const d=await getResume(id);title.value=d.title;template.value=d.template||'ats-modern';resume.value=ensureShape(d.data)}catch(e){error.value=e.message}}
async function save(){if(!id)return;saving.value=true;saved.value=false;resume.value.language=cvLanguage.value;try{await updateResume(id,{title:title.value,template:template.value,data:resume.value});saved.value=true;setTimeout(()=>saved.value=false,1200)}catch(e){error.value=e.message}finally{saving.value=false}}
watch([resume,title,template],()=>{clearTimeout(timer);timer=setTimeout(save,650)},{deep:true})
function add(type){const rows={experience:{role:'',company:'',period:'',description:''},education:{degree:'',school:'',period:''},projects:{name:'',link:'',description:''},languages:{name:'',level:''}};if(type==='skills')resume.value.skills.push('');else resume.value[type].push({...rows[type]})}
function remove(type,i){resume.value[type].splice(i,1)}
function printPdf(){window.print()}
const health = computed(()=>{let score=0;const tips=[];const p=resume.value.personal;if(p.name&&p.email&&p.phone)score+=15;else tips.push('Complete your contact details');if(p.title)score+=8;else tips.push('Add a clear target job title');if((p.summary||'').length>=80)score+=14;else tips.push('Write a focused 2–4 line professional summary');if(resume.value.experience.length)score+=18;else tips.push('Add at least one relevant work experience');if(resume.value.experience.some(x=>/\d+%|\$\d+|\d+\+|\d+\s*(users|clients|projects|hours|days)/i.test(x.description||'')))score+=12;else tips.push('Add measurable outcomes where they are truthful and useful');if(resume.value.education.length)score+=8;if(resume.value.skills.filter(Boolean).length>=6)score+=12;else tips.push('Add 6–12 relevant skills');if(atsTemplates.includes(template.value))score+=8;else score+=5;if(p.linkedin||p.website)score+=5;return{score:Math.min(100,score),tips:tips.slice(0,4)}})
function addSkill(skill){if(!(resume.value.skills||[]).some(x=>x.toLowerCase()===skill.toLowerCase()))resume.value.skills.push(skill)}
function useSummary(text){resume.value.personal.summary=text}
function addResponsibility(text,index=null){if(index===null){if(!resume.value.experience.length)add('experience');index=0}const current=resume.value.experience[index].description?.trim()||'';resume.value.experience[index].description=current?`${current}\n• ${text}`:`• ${text}`}
function suggestForExperience(index){const role=resume.value.experience[index].role||resume.value.personal.title;const ideas=suggestedResponsibilities(role);const current=resume.value.experience[index].description?.trim()||'';const first=ideas.find(x=>!current.includes(x))||ideas[0];resume.value.experience[index].description=current?`${current}\n• ${first}`:`• ${first}`}
function changeCvLanguage(lang,translate=false){if(translate)resume.value=ensureShape(translateResume(resume.value,lang));cvLanguage.value=lang;resume.value.language=lang;showLanguageMenu.value=false}
const ui = computed(()=>cvLanguage.value==='ar'?{
  personal:'البيانات الشخصية',name:'الاسم',professionalTitle:'المسمى الوظيفي',email:'البريد الإلكتروني',phone:'الهاتف',location:'الموقع',linkedin:'لينكدإن',website:'الموقع الإلكتروني',summary:'الملخص المهني',experience:'الخبرات العملية',education:'التعليم',projects:'المشاريع',skills:'المهارات',languages:'اللغات',add:'إضافة',export:'تصدير PDF',dashboard:'لوحة التحكم',role:'المنصب',company:'الشركة',period:'الفترة',description:'الوصف',degree:'الشهادة / الاختصاص',school:'الجامعة / المعهد',projectName:'اسم المشروع',link:'الرابط',language:'اللغة',level:'المستوى',suggest:'اقترح إنجازاً مهنياً'
}:{personal:'Personal details',name:'Name',professionalTitle:'Professional title',email:'Email',phone:'Phone',location:'Location',linkedin:'LinkedIn',website:'Website',summary:'Professional summary',experience:'Experience',education:'Education',projects:'Projects',skills:'Skills',languages:'Languages',add:'Add',export:'Export PDF',dashboard:'Dashboard',role:'Role',company:'Company',period:'Period',description:'Description',degree:'Degree',school:'School',projectName:'Project name',link:'Link',language:'Language',level:'Level',suggest:'Suggest an achievement bullet'})
onMounted(load)
</script>

<template><div class="builder">
<header class="builder-top"><button class="back" @click="router.push('/dashboard')">← {{ui.dashboard}}</button><input class="title-input" v-model="title"><div class="builder-actions"><span>{{saving?'Saving…':(saved?'Saved ✓':'Autosave')}}</span><select v-model="template" class="template-select"><optgroup label="ATS Friendly"><option v-for="t in atsOptions" :key="t.template" :value="t.template">{{t.name}}</option></optgroup><optgroup label="Creative"><option v-for="t in creativeOptions" :key="t.template" :value="t.template">{{t.name}}</option></optgroup></select><div class="cv-lang-switch"><button class="ghost share-btn" @click="showLanguageMenu=!showLanguageMenu">{{cvLanguage==='ar'?'العربية':'English'}} ▾</button><div v-if="showLanguageMenu" class="cv-lang-menu"><small class="lang-menu-label">DISPLAY LANGUAGE</small><button @click="changeCvLanguage('en',false)">English interface</button><button @click="changeCvLanguage('ar',false)">واجهة عربية</button><hr><small class="lang-menu-label">TRANSLATE CV CONTENT</small><button @click="changeCvLanguage('en',true)">Translate → English</button><button @click="changeCvLanguage('ar',true)">ترجمة → العربية</button></div></div><button class="ghost share-btn typography-btn" @click="showTypography=!showTypography">Aa {{activeFont}}</button><ThemeToggle/><button class="btn" @click="printPdf">{{ui.export}}</button></div></header>
<div v-if="error" class="error builder-error">{{error}}</div>
<div class="builder-body"><section class="editor" :dir="cvLanguage==='ar'?'rtl':'ltr'">
<div class="editor-intro"><div><span class="eyebrow">RESUME STUDIO</span><h1>{{cvLanguage==='ar'?'ابنِ سيرتك بثقة.':'Build with clarity. Apply with confidence.'}}</h1><p class="editor-sub">{{cvLanguage==='ar'?'اكتب محتوى واضحاً، اختر من 14 قالباً، واحفظ كل شيء محلياً في متصفحك.':'Write stronger content, explore 14 layouts and keep everything auto-saved in this browser.'}}</p></div><div class="editor-tools"><span :class="['template-mode',atsTemplates.includes(template)?'safe':'creative']">{{atsTemplates.includes(template)?'ATS Friendly':'Creative Layout'}}</span></div></div>
<div v-if="showTypography" class="typography-studio"><div class="typography-head"><div><span class="eyebrow">TYPOGRAPHY STUDIO</span><h3>{{cvLanguage==='ar'?'اختر خط السيرة الذاتية':'Choose your resume font'}}</h3><p>{{cvLanguage==='ar'?'يتم تطبيق الخط مباشرة ويتم حفظه مع هذه السيرة.':'The font is applied instantly and saved with this resume.'}}</p></div><button class="modal-x typo-close" @click="showTypography=false">×</button></div><div class="font-grid"><button v-for="font in activeFontList" :key="font.id" :class="['font-card',{active:activeFont===font.id}]" @click="setResumeFont(font.id)" :style="{fontFamily:`'${font.id}', sans-serif`}"><span class="font-check">{{activeFont===font.id?'✓':'Aa'}}</span><strong>{{font.name}}</strong><small>{{font.sample}}</small></button></div><div class="font-note"><span>✦</span><p>{{cvLanguage==='ar'?'نصيحة: اختر خطاً واضحاً ومتناسقاً، وقلّل الزخرفة عندما تكون القراءة السريعة أهم.':'Tip: prioritize readability and consistency. Let typography support your content rather than compete with it.'}}</p></div></div>
<div class="smart-start-grid"><div class="builder-tip-card"><span>✦</span><div><b>Make the first 10 seconds count</b><small>Lead with a clear title, a focused summary and your most relevant experience.</small></div></div><div class="health-card"><div class="health-ring" :style="{'--score':health.score}"><div class="health-score"><strong>{{health.score}}</strong><span>/100</span></div></div><div class="health-copy"><div class="health-title-row"><b>Resume Health</b><span :class="['health-status',health.score>=80?'great':health.score>=60?'good':'needs-work']">{{health.score>=80?'Strong':health.score>=60?'Good':'Needs work'}}</span></div><small v-if="health.score>=80">Strong foundation — polish the final details.</small><small v-else>{{health.tips[0]||'Looking good'}}</small><div class="health-progress"><i :style="{width:health.score+'%'}"></i></div></div></div></div>
<h2>{{ui.personal}}</h2><div class="two"><label>{{ui.name}}<input v-model="resume.personal.name" placeholder="Alex Morgan"></label><label>{{ui.professionalTitle}}<input v-model="resume.personal.title" placeholder="Frontend Developer"></label><label>{{ui.email}}<input v-model="resume.personal.email" placeholder="alex@email.com"></label><label>{{ui.phone}}<input v-model="resume.personal.phone" placeholder="+1 555 123 4567"></label><label>{{ui.location}}<input v-model="resume.personal.location" placeholder="San Francisco, CA"></label><label>{{ui.linkedin}}<input v-model="resume.personal.linkedin" placeholder="linkedin.com/in/name"></label></div><label>{{ui.website}}<input v-model="resume.personal.website" placeholder="portfolio.com"></label>
<CareerAssistant :title="resume.personal.title" :resume="resume" @add-skill="addSkill" @use-summary="useSummary" @add-responsibility="addResponsibility"/>
<label>{{ui.summary}}<textarea v-model="resume.personal.summary" rows="5" placeholder="Write a concise career summary..."></textarea></label>
<div class="section-head"><h2>{{ui.experience}}</h2><button @click="add('experience')">＋ {{ui.add}}</button></div><div class="entry" v-for="(x,i) in resume.experience" :key="i"><button class="x" @click="remove('experience',i)">×</button><div class="two"><label>{{ui.role}}<input v-model="x.role" placeholder="Frontend Developer"></label><label>{{ui.company}}<input v-model="x.company" placeholder="Company name"></label></div><label>{{ui.period}}<input v-model="x.period" placeholder="2023 — Present"></label><label>{{ui.description}}<textarea v-model="x.description" rows="5" placeholder="Focus on impact, outcomes and measurable results."></textarea></label><button class="inline-assist" @click="suggestForExperience(i)">✦ {{ui.suggest}}</button></div>
<div class="section-head"><h2>{{ui.education}}</h2><button @click="add('education')">＋ {{ui.add}}</button></div><div class="entry" v-for="(x,i) in resume.education" :key="i"><button class="x" @click="remove('education',i)">×</button><div class="two"><label>{{ui.degree}}<input v-model="x.degree"></label><label>{{ui.school}}<input v-model="x.school"></label></div><label>{{ui.period}}<input v-model="x.period"></label></div>
<div class="section-head"><h2>{{ui.projects}}</h2><button @click="add('projects')">＋ {{ui.add}}</button></div><div class="entry" v-for="(x,i) in resume.projects" :key="i"><button class="x" @click="remove('projects',i)">×</button><div class="two"><label>{{ui.projectName}}<input v-model="x.name"></label><label>{{ui.link}}<input v-model="x.link"></label></div><label>{{ui.description}}<textarea v-model="x.description" rows="3"></textarea></label></div>
<div class="section-head"><h2>{{ui.skills}}</h2><button @click="add('skills')">＋ {{ui.add}}</button></div><div class="skill-input" v-for="(s,i) in resume.skills" :key="i"><input v-model="resume.skills[i]" placeholder="Vue.js"><button @click="remove('skills',i)">×</button></div>
<div class="section-head"><h2>{{ui.languages}}</h2><button @click="add('languages')">＋ {{ui.add}}</button></div><div class="entry compact-entry" v-for="(x,i) in resume.languages" :key="i"><button class="x" @click="remove('languages',i)">×</button><div class="two"><label>{{ui.language}}<input v-model="x.name"></label><label>{{ui.level}}<input v-model="x.level" placeholder="Fluent"></label></div></div>
<div class="resume-checklist"><div><span class="eyebrow">FINAL CHECK</span><h3>{{health.score}}/100 Resume Health</h3></div><ul><li v-for="tip in health.tips" :key="tip">{{tip}}</li><li v-if="!health.tips.length">Your resume covers the core quality checks ✓</li></ul></div>
</section><aside class="preview-pane"><ResumePreview :resume="resume" :template="template" :language="cvLanguage" :font-family="activeFont"/></aside></div>
</div></template>
