<script setup>
import { onMounted,onBeforeUnmount } from 'vue'
import SiteNav from '../components/SiteNav.vue'
import SiteFooter from '../components/SiteFooter.vue'
let io
onMounted(()=>{io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el))})
onBeforeUnmount(()=>io?.disconnect())
</script>
<template><main class="landing"><SiteNav/>
<section class="hero wrap"><div class="hero-copy reveal visible"><div class="pill">✦ Private, local resume workspace</div><h1>Build a resume that feels <em>clear, confident and yours.</em></h1><p>Create focused resume versions, switch across 14 professional layouts, get practical writing guidance and export polished PDFs — no account required.</p><div class="hero-actions"><router-link to="/dashboard" class="btn big">Open my workspace <span>↗</span></router-link><router-link to="/templates" class="ghost big">Explore 14 templates</router-link></div><div class="trust-row"><div><strong>14</strong><span>professional templates</span></div><div><strong>2</strong><span>English + Arabic</span></div><div><strong>0</strong><span>accounts required</span></div></div></div>
<div class="hero-visual reveal visible"><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="floating-chip chip-one">✓ Auto-saved locally</div><div class="floating-chip chip-two">✦ Resume health guidance</div><div class="hero-card premium"><div class="mini-toolbar"><i></i><i></i><i></i><span>Live Preview</span></div><div class="resume-mini"><div class="mini-name"><h3>Alex Morgan</h3><small>Product Designer</small></div><hr/><h4>PROFILE</h4><p>Product designer focused on simple experiences, useful systems and measurable impact.</p><h4>EXPERIENCE</h4><b>Senior Product Designer</b><p>Led product design across web and mobile, improving activation and retention.</p><h4>SKILLS</h4><div class="tags"><span>Figma</span><span>UX</span><span>Research</span><span>Systems</span></div></div></div></div></section>
<section class="logo-strip"><div class="wrap"><span>Built for careers in</span><b>TECH</b><b>DESIGN</b><b>FINANCE</b><b>MARKETING</b><b>OPERATIONS</b><b>CONSULTING</b></div></section>
<section id="features" class="section wrap"><div class="section-headline reveal"><span class="eyebrow">THE WORKSPACE</span><h2>Everything you need to turn your experience into a <em>stronger story.</em></h2><p>Focused tools, local autosave and enough design choice without turning your resume into a design project.</p></div><div class="feature-bento"><article class="feature-card large reveal"><span class="feature-icon">✦</span><h3>Live Resume Builder</h3><p>Edit your content and watch the final resume update instantly beside you.</p><div class="mini-editor-ui"><div class="field-line wide"></div><div class="field-line"></div><div class="field-line short"></div><div class="preview-pane-mini"></div></div></article><article class="feature-card reveal"><span class="feature-icon">◫</span><h3>14 Templates</h3><p>Seven ATS-friendly designs and seven creative layouts — switch anytime.</p><div class="swatches"><i></i><i></i><i></i></div></article><article class="feature-card reveal"><span class="feature-icon">☾</span><h3>Dark Mode</h3><p>A polished light and dark workspace that remembers your preference.</p></article><article class="feature-card reveal"><span class="feature-icon">✓</span><h3>Resume Health</h3><p>Practical local checks for completeness, clarity, measurable impact and useful details.</p></article><article class="feature-card wide-card reveal"><span class="feature-icon">↗</span><div><h3>One-click PDF export</h3><p>Print or save a clean A4 resume whenever you are ready.</p></div><div class="pdf-card">PDF <b>↓</b></div></article></div></section>
<section class="dark-section"><div class="wrap"><div class="section-headline light-text reveal"><span class="eyebrow">DESIGN WITH A PURPOSE</span><h2>ATS-friendly when you need simplicity. <em>Creative when presentation matters.</em></h2></div><div class="mode-grid"><article class="mode-card reveal"><span class="kind-badge ats">ATS FRIENDLY · 7</span><h3>Clear, structured, readable</h3><p>Single-column and conservative layouts built around standard sections and easy scanning.</p><ul><li>Clean content hierarchy</li><li>Readable typography</li><li>Professional spacing</li></ul><router-link to="/templates">See ATS-friendly templates →</router-link></article><article class="mode-card creative-mode reveal"><span class="kind-badge creative">CREATIVE · 7</span><h3>Distinctive without the clutter</h3><p>More expressive typography, sidebars and visual rhythm for direct applications and creative roles.</p><ul><li>Editorial layouts</li><li>Strong personal presence</li><li>Portfolio-friendly design</li></ul><router-link to="/templates">See creative templates →</router-link></article></div></div></section>
<section id="tips" class="section wrap resume-tips-section"><div class="section-headline reveal"><span class="eyebrow">RESUME GUIDANCE</span><h2>Small improvements make a <em>big difference.</em></h2><p>Use these principles while you build — they work across industries and experience levels.</p></div><div class="tip-grid"><article class="reveal"><span>01</span><h3>Start with relevance</h3><p>Your resume is not your full biography. Prioritize the experience, skills and proof that support the role you want next.</p></article><article class="reveal"><span>02</span><h3>Show impact</h3><p>Replace vague duties with outcomes. Describe what you improved, delivered, saved, grew or simplified.</p></article><article class="reveal"><span>03</span><h3>Make it easy to scan</h3><p>Short paragraphs, consistent dates, clear headings and focused bullets help the important information surface quickly.</p></article><article class="reveal"><span>04</span><h3>Finish with confidence</h3><p>Proofread the final PDF, check links and contact details, then send the version that best fits the opportunity.</p></article></div><div class="motivation-card reveal"><span>✦</span><div><h3>Your experience already happened. The resume’s job is to make it easy to understand.</h3><p>You do not need to sound impressive — you need to be specific, relevant and clear.</p></div><router-link to="/dashboard" class="btn">Start building →</router-link></div></section>
<section class="pricing-section"><div class="wrap pricing-box reveal"><div><span class="eyebrow">SIMPLE BY DESIGN</span><h2>Your resume workspace. No account wall.</h2><p>Your name and resumes stay in this browser. Create multiple versions, switch templates, use dark mode and export whenever you are ready.</p></div><div class="price product-value"><strong>Local</strong><small>private · fast · no backend</small><router-link to="/dashboard" class="btn">Open workspace</router-link></div></div></section>
<SiteFooter/></main></template>
